/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Master;

import Koneksi.db;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class FormDataKaryawan extends javax.swing.JFrame {
    private Connection conn = new db().connect();
    private boolean editMode = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDataKaryawan.class.getName());

    /**
     * Creates new form FormDataKaryawan
     */
    public FormDataKaryawan() {
        initComponents();
        kosong();
        aktif();
        tampilJabatan();
    }
    
    protected void aktif (){
        idk.requestFocus();
    }
    protected void kosong(){
        idk.setText("");
        nmk.setText("");
        buttonGroup1.clearSelection();
        ak.setText("");
        ntk.setText("");
        jabatan.setSelectedItem(null);
    }
    public void setData(String id, String nama, String jk, String alamat, String telp, String jab){
        idk.setText(id);
        nmk.setText(nama);
        if(jk.equals("Laki-Laki")){
            lkariawan.setSelected(true);
        } else {
            pkariawan.setSelected(true);
        }
        ak.setText(alamat);
        ntk.setText(telp);
        jabatan.setSelectedItem(jab);
        idk.setEditable(false);
        editMode = true;
    }
    
    private void tampilJabatan() {
        try {
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM jabatan";
            ResultSet rs = st.executeQuery(sql);
            jabatan.removeAllItems();
            while (rs.next()) {
                jabatan.addItem(rs.getString("nm_jabatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal menampilkan data jabatan : " + e.getMessage());
        }
    }
    
    private String getIdJabatan(String namaJabatan){
        String id = "";
        try{
            String sql = "SELECT id_jabatan FROM jabatan WHERE nm_jabatan=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, namaJabatan);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                id = rs.getString("id_jabatan");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idk = new javax.swing.JTextField();
        nmk = new javax.swing.JTextField();
        ak = new javax.swing.JTextField();
        ntk = new javax.swing.JTextField();
        jabatan = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lkariawan = new javax.swing.JRadioButton();
        pkariawan = new javax.swing.JRadioButton();
        tabel = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("FORM DATA KARYAWAN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Karyawan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Karyawan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("No. Telepon");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jabatan");

        idk.addActionListener(this::idkActionPerformed);

        nmk.addActionListener(this::nmkActionPerformed);

        ntk.addActionListener(this::ntkActionPerformed);

        jabatan.addActionListener(this::jabatanActionPerformed);

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(this::bsimpanActionPerformed);

        bubah.setText("Ubah");
        bubah.addActionListener(this::bubahActionPerformed);

        bbatal.setText("Batal");
        bbatal.addActionListener(this::bbatalActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        buttonGroup1.add(lkariawan);
        lkariawan.setText("Laki-Laki");

        buttonGroup1.add(pkariawan);
        pkariawan.setText("Perempuan");
        pkariawan.addActionListener(this::pkariawanActionPerformed);

        tabel.setText("Tabel");
        tabel.addActionListener(this::tabelActionPerformed);

        kembali.setText("Kembali");
        kembali.addActionListener(this::kembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lkariawan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pkariawan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nmk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(86, 86, 86)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ntk)
                                        .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(bubah)
                        .addGap(18, 18, 18)
                        .addComponent(bbatal)
                        .addGap(18, 18, 18)
                        .addComponent(tabel)
                        .addGap(18, 18, 18)
                        .addComponent(kembali)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nmk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lkariawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pkariawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ak, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ntk, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jabatan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void idkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idkActionPerformed

    private void nmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmkActionPerformed

    private void ntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntkActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        
    }//GEN-LAST:event_jabatanActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // Validasi input kosong
        if(idk.getText().trim().equals("") ||
           nmk.getText().trim().equals("") ||
           ak.getText().trim().equals("") ||
           ntk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Data harus diisi semua!");
            return;
        }
        // Validasi jenis kelamin
        if(!lkariawan.isSelected() && !pkariawan.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin terlebih dahulu!");
            return;
        }
        // Validasi jabatan
        if(jabatan.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Pilih jabatan terlebih dahulu!");
            return;
        }
        // Validasi No Telepon (Harus Angka)
        if(!ntk.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null,
                    "Nomor telepon hanya boleh angka!");
            ntk.requestFocus();
            return;
        }
        String jenis = null;
        if(lkariawan.isSelected()){
            jenis = "Laki-Laki";
        }else if(pkariawan.isSelected()){
            jenis = "Perempuan";
        }
        String sql = "insert into karyawan values (?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, idk.getText());
            stat.setString(2, nmk.getText());
            stat.setString(3, jenis);
            stat.setString(4, ak.getText());
            stat.setString(5, ntk.getText());
            String idJabatan = getIdJabatan(jabatan.getSelectedItem().toString());
            stat.setString(6, idJabatan);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            idk.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
               
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
       kosong();
    }//GEN-LAST:event_bbatalActionPerformed

    private void pkariawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkariawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkariawanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        String jenis = null;
        if(lkariawan.isSelected()){
            jenis = "Laki-Laki";
        }else if(pkariawan.isSelected()){
            jenis = "Perempuan";
        }
        if(editMode == false){
        JOptionPane.showMessageDialog(null, "Pilih data dari tabel dulu!");
        return;
        }
        try{
            String sql = "UPDATE karyawan SET nm_karyawan=?, jk=?, alamat=?, telp=?, id_jabatan=? WHERE id_karyawan=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nmk.getText());
            stat.setString(2, jenis);
            stat.setString(3, ak.getText());
            stat.setString(4, ntk.getText());
            String idJabatan = getIdJabatan(jabatan.getSelectedItem().toString());
            stat.setString(5, idJabatan);
            stat.setString(6, idk.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            editMode = false;
            idk.setEditable(true);
            kosong();
            idk.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah: "+e);
        }
    }//GEN-LAST:event_bubahActionPerformed

    private void tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelActionPerformed
        Master.TabelKaryawan tk = new Master.TabelKaryawan();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabelActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Login.MainMenu mn = new Login.MainMenu();
        mn.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDataKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ak;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JButton kembali;
    private javax.swing.JRadioButton lkariawan;
    private javax.swing.JTextField nmk;
    private javax.swing.JTextField ntk;
    private javax.swing.JRadioButton pkariawan;
    private javax.swing.JButton tabel;
    // End of variables declaration//GEN-END:variables
}
